### ISSUE TITLE
Tighter pinning

### ISSUE THREAD

**Issue by pelson** [conda-forge/numpy-feedstock#1]
We should be pinning against `openblas 0.2.18*`, not `openblas 0.2*`:
```
otool -L /Users/pelson/miniconda/envs/cf_np/lib/python3.4/site-packages/numpy/linalg/lapack_lite.so 
/Users/pelson/miniconda/envs/cf_np/lib/python3.4/site-packages/numpy/linalg/lapack_lite.so:
	@rpath/libopenblas-r0.2.18.dylib (compatibility version 0.0.0, current version 0.0.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)
```

**Comment by jakirkham** [comment]
That's right. They do encode the full version in the library. Thanks for reminding me. Though I don't think they ever use a 4th version number, using `*` shouldn't hurt anything. It does feel a little ridiculous to need to pin this so tightly as we are not using any of the OpenBLAS specific API, but are just using standard BLAS and LAPACK routines. Not sure there is anything we can do about it though.

**Comment by jakirkham** [comment]
Will be fixed in this PR ( https://github.com/conda-forge/numpy-feedstock/pull/6 ).

**Comment by jakirkham** [comment]
Done in `master`. Probably worth rebasing or merging with it
