### ISSUE TITLE
Fortran openblas link error

### ISSUE THREAD

**Issue by cdeil** [conda-forge/numpy-feedstock#124]
Since about a week ago, the Numpy dev build with a Python from miniconda started failing to link against fortran:
/home/travis/miniconda/envs/test/lib/libopenblas.so: undefined reference to `_gfortran_concat_string@GFORTRAN_7'
  /home/travis/miniconda/envs/test/lib/libopenblas.so: undefined reference to `_gfortran_etime@GFORTRAN_7'
  collect2: error: ld returned 1 exit status
```
Log is here: https://travis-ci.org/gammapy/gammapy/jobs/482838855#L1597
Some comments / attempts to fix it are here: https://github.com/gammapy/gammapy/pull/1997

To reproduce:
```
$ docker run -it ubuntu
apt-get update
apt-get install wget git
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
bash Miniconda3-latest-Linux-x86_64.sh
source ~/.bashrc
conda install cython numpy
pip install -U git+https://github.com/numpy/numpy.git#egg=numpy # fails
```
This fixes the error locally in Docker, but not on travis-ci:
```
apt install gcc
pip install -U git+https://github.com/numpy/numpy.git#egg=numpy # works
```
I'm not sure why, I thought conda ships compilers? Maybe not and I have to execute some conda install command to get the appropriate compilers to build numpy now?

I thought I'd mention it here, in case this is a regression in the Numpy build system or Numpy conda packages. (we didn't change anything about our CI build and it worked for the past months).

**Comment by isuruf** [comment]
You are installing `libgfortran` which conflicts with `libgfortran-ng`
