### ISSUE TITLE
create a 1.15 branch

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/numpy-feedstock#137]
Would be good to have that branch point so we can rebuild 1.15 for aarch64 and ppc64le

Seems like it should be pointing to:
https://github.com/conda-forge/numpy-feedstock/commit/33ba79c1aa808525aab8151ed6d3ec6d4612b88d

@conda-forge/arm-arch

**Comment by mariusvniekerk** [comment]
Done
