### ISSUE TITLE
conda-forge install numpy  gets mkl from defaults?

### ISSUE THREAD

**Issue by flutefreak7** [conda-forge/numpy-feedstock#153]
I'm trying to understand what's going on with conda-forge numpy install.  I thought there was a big issue with conda-forge's numpy relying on openblas as opposed to the defaults numpy relying on mkl. When I attempt to install numpy into a fresh miniconda environment, however, I see mkl coming from defaults?  I don't actually care - I wouldn't mind having mkl, but I want a functioning environment and require some things from conda-forge, so I figured I'd start by installing everything from conda-forge to avoid any nasty binary incompatibility issues or the "mkl openblas dance".  Will I be ok using mkl from defaults with numpy from conda-forge?  On windows, do I need to worry at all about whether things come from defaults or conda-forge or are things mostly compatible now? I've seen all sorts of issues and warnings against doing that, but with things like scipy and numba not working on conda-forge for Windows, it's impossible to form a conda-forge only environment anyway.

```
(base) C:\Miniconda3\Scripts>conda install --channel conda-forge conda-forge::numpy
Collecting package metadata: done
Solving environment: done

## Package Plan ##

  environment location: C:\Miniconda3

  added / updated specs:
    - conda-forge::numpy


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ca-certificates-2019.3.9   |       hecc5488_0         184 KB  conda-forge
    certifi-2019.3.9           |           py37_0         149 KB  conda-forge
    conda-4.6.8                |           py37_0         897 KB  conda-forge
    intel-openmp-2019.3        |              203         1.7 MB
    libblas-3.8.0              |            4_mkl         3.5 MB  conda-forge
    libcblas-3.8.0             |            4_mkl         3.5 MB  conda-forge
    liblapack-3.8.0            |            4_mkl         3.5 MB  conda-forge
    mkl-2019.1                 |              144       158.3 MB
    numpy-1.16.2               |   py37h8078771_1         4.0 MB  conda-forge
    openssl-1.1.1b             |       hfa6e2cd_2         4.8 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       180.5 MB

The following NEW packages will be INSTALLED:

  intel-openmp       pkgs/main/win-64::intel-openmp-2019.3-203
  libblas            conda-forge/win-64::libblas-3.8.0-4_mkl
  libcblas           conda-forge/win-64::libcblas-3.8.0-4_mkl
  liblapack          conda-forge/win-64::liblapack-3.8.0-4_mkl
  mkl                pkgs/main/win-64::mkl-2019.1-144
  numpy              conda-forge/win-64::numpy-1.16.2-py37h8078771_1

The following packages will be UPDATED:

  ca-certificates    pkgs/main::ca-certificates-2019.1.23-0 --> conda-forge::ca-certificates-2019.3.9-hecc5488_0
  openssl              pkgs/main::openssl-1.1.1b-he774522_1 --> conda-forge::openssl-1.1.1b-hfa6e2cd_2

The following packages will be SUPERSEDED by a higher-priority channel:

  certifi                                         pkgs/main --> conda-forge
  conda                                           pkgs/main --> conda-forge


Proceed ([y]/n)?
```

**Comment by isuruf** [comment]
As of a week ago, conda-forge::numpy is compatible with mkl from defaults and scipy from defaults. See https://conda-forge.org/docs/maintainer/knowledge_base.html#blas
Note that you can install a conda-forge::numpy depending on openblas by doing `conda install conda-forge::numpy "blas=*=openblas"`, but you can't install scipy into this environment. When you do `conda install conda-forge::numpy scipy` you'll get scipy from defaults (as there's no scipy in conda-forge on windows) which is only compatible with mkl.

**Comment by flutefreak7** [comment]
@isuruf Ok, good to know! Thanks! If I must mix packages between conda-forge and defaults, which should I prefer? I also need numba for example, which isn't in conda-forge. It only makes sense to me to use numba and numpy from the same source... then pandas and matplotlib, etc... then just use conda-forge for stuff not in defaults like pyqtgraph.

**Comment by hermidalc** [comment]
@isuruf using your referenced instructions I switched to `mkl` as my backend blas implementation using `conda install "libblas=*=*mkl"` but why then does `conda update --all` want to go back to the `openblas` backend?
```bash
The following packages will be REMOVED:

  intel-openmp-2019.4-243
  mkl-2019.4-243

The following packages will be DOWNGRADED:

  libblas                                      3.8.0-10_mkl --> 3.8.0-10_openblas
  libcblas                                     3.8.0-10_mkl --> 3.8.0-10_openblas
  liblapack                                    3.8.0-10_mkl --> 3.8.0-10_openblas
  liblapacke                                   3.8.0-10_mkl --> 3.8.0-10_openblas
```

**Comment by isuruf** [comment]
@jjhelmus, any ideas?

**Comment by jjhelmus** [comment]
I can replicate this.  Without a lot more information (conda info, conda list --show-channel-urls) and knowing a bit about the history of the environment it is very difficult to debug these type of issues.

**Comment by isuruf** [comment]
@jjhelmus, I can replicate this by creating a new env `conda create -n numpy-test numpy libblas=*=*mkl` and then doing `conda update --all`. Let me know if you need more info. (Did you mean can or can't?)

**Comment by jjhelmus** [comment]
@isuruf Sorry that should be I can't replicate.  What is the output of `conda info` and your .condarc?  When I run the following with conda 4.7.10 and no modification to the default .condarc:

```
conda create -y -n test -c conda-forge numpy libblas=*=*mkl
conda update -n test -c conda-forge --all
```
I do not get any updates.

**Comment by isuruf** [comment]
```bash
(base) isuru@isuru:~/projects/qt-feedstock$ conda info

     active environment : base
    active env location : /home/isuru/miniconda3
            shell level : 1
       user config file : /home/isuru/.condarc
 populated config files : /home/isuru/miniconda3/.condarc
                          /home/isuru/.condarc
          conda version : 4.7.8
    conda-build version : 3.17.8
         python version : 3.6.7.final.0
       virtual packages : 
       base environment : /home/isuru/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/isuru/miniconda3/pkgs
                          /home/isuru/.conda/pkgs
       envs directories : /home/isuru/miniconda3/envs
                          /home/isuru/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.8 requests/2.22.0 CPython/3.6.7 Linux/4.15.0-54-generic ubuntu/18.04.2 glibc/2.27
                UID:GID : 1000:1000
             netrc file : /home/isuru/.netrc
           offline mode : False

(base) isuru@isuru:~/projects/qt-feedstock$ cat ~/.condarc
channels:
  - conda-forge
  - defaults
```

And here's the output when creating and updating,

```
(base) isuru@isuru:~/projects/qt-feedstock$ conda create -n numpy-test numpy libblas=*=*mkl
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.8
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/isuru/miniconda3/envs/numpy-test

  added / updated specs:
    - libblas[build=*mkl]
    - numpy


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  bzip2              conda-forge/linux-64::bzip2-1.0.8-h516909a_0
  ca-certificates    conda-forge/linux-64::ca-certificates-2019.6.16-hecc5488_0
  certifi            conda-forge/linux-64::certifi-2019.6.16-py37_1
  intel-openmp       pkgs/main/linux-64::intel-openmp-2019.4-243
  libblas            conda-forge/linux-64::libblas-3.8.0-10_mkl
  libcblas           conda-forge/linux-64::libcblas-3.8.0-10_mkl
  libffi             conda-forge/linux-64::libffi-3.2.1-he1b5a44_1006
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  liblapack          conda-forge/linux-64::liblapack-3.8.0-10_mkl
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  mkl                pkgs/main/linux-64::mkl-2019.4-243
  ncurses            conda-forge/linux-64::ncurses-6.1-hf484d3e_1002
  numpy              conda-forge/linux-64::numpy-1.16.4-py37h95a1406_0                                                                                                
  openssl            conda-forge/linux-64::openssl-1.1.1c-h516909a_0                                                                                                  
  pip                conda-forge/linux-64::pip-19.1.1-py37_0                                                                                                          
  python             conda-forge/linux-64::python-3.7.3-h33d41f4_1                                                                                                    
  readline           conda-forge/linux-64::readline-8.0-hf8c457e_0                                                                                                    
  setuptools         conda-forge/linux-64::setuptools-41.0.1-py37_0
  sqlite             conda-forge/linux-64::sqlite-3.29.0-hcee41ef_0
  tk                 conda-forge/linux-64::tk-8.6.9-hed695b0_1002
  wheel              conda-forge/linux-64::wheel-0.33.4-py37_0
  xz                 conda-forge/linux-64::xz-5.2.4-h14c3975_1001
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1005


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: \ 
SafetyError: The package for mkl located at /home/isuru/miniconda3/pkgs/mkl-2019.4-243
appears to be corrupted. The path 'lib/libmkl_rt.so'
has an incorrect size.
  reported size: 6617050 bytes
  actual size: 7872 bytes


done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate numpy-test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

(base) isuru@isuru:~/projects/qt-feedstock$ conda activate numpy-test
(numpy-test) isuru@isuru:~/projects/qt-feedstock$ conda update --all
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.8
  latest version: 4.7.10

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /home/isuru/miniconda3/envs/numpy-test


The following NEW packages will be INSTALLED:

  libgfortran-ng     pkgs/main/linux-64::libgfortran-ng-7.3.0-hdf63c60_0
  libopenblas        conda-forge/linux-64::libopenblas-0.3.6-h6e990d7_4
  openblas           conda-forge/linux-64::openblas-0.3.6-h6e990d7_4

The following packages will be REMOVED:

  intel-openmp-2019.4-243
  mkl-2019.4-243

The following packages will be DOWNGRADED:

  libblas                                      3.8.0-10_mkl --> 3.8.0-10_openblas
  libcblas                                     3.8.0-10_mkl --> 3.8.0-10_openblas
  liblapack                                    3.8.0-10_mkl --> 3.8.0-10_openblas


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```

**Comment by jjhelmus** [comment]
Ah, I missed that this was on linux not windows which what the OP was discussing.  I can replicate this now and will look into it, not sure why the historic spec is being ignored.

**Comment by hermidalc** [comment]
@jjhelmus @isuruf my apologies maybe should've opened a separate issue for this.  Yes I'm on Linux and thanks in advance.

**Comment by jjhelmus** [comment]
`conda update --all` drops all historic package specifications.  The assumptions is that you are asking conda to update all the package in an environment to their latest versions.  The same thing happens if you request a particular version of a package and then run `conda update --all`, you get the latest version.  If you want a specification to be respected by `update --all` you need to pin the package rather than just request it.

**Comment by jjhelmus** [comment]
Creating a files named "pinned" in the conda-meta directory containing: `libblas[build=*mkl]` will keep the mkl variant of libblas and friends around through a `conda update --all`

**Comment by hermidalc** [comment]
Though my confusion here is that it's not updating all the packages to their latest versions?  It's changing your (blas) packages to others of the same version.  Maybe just my not understanding the `update` logic.

**Comment by isuruf** [comment]
@hermidalc, the `openblas` variants have "higher priority" in linux. That's why without the history spec, the mkl builds gets replaced by openblas.

**Comment by hermidalc** [comment]
> @hermidalc, the `openblas` variants have "higher priority" in linux. That's why without the history spec, the mkl builds gets replaced by openblas.

Ah ok, now that makes sense... it's not just version numbers but also package priorities.  Great thank you both, I will create a pinned file and problem solved.

**Comment by ChiHangChen** [comment]
> As of a week ago, conda-forge::numpy is compatible with mkl from defaults and scipy from defaults. See https://conda-forge.org/docs/maintainer/knowledge_base.html#blas
> Note that you can install a conda-forge::numpy depending on openblas by doing `conda install conda-forge::numpy "blas=*=openblas"`, but you can't install scipy into this environment. When you do `conda install conda-forge::numpy scipy` you'll get scipy from defaults (as there's no scipy in conda-forge on windows) which is only compatible with mkl.

Great!! This answer reduce my pyinstaller exe file from 233MB to 64MB!!!

**Comment by mario0man** [comment]
@ChiHangChen How did you force pyinstaller to use the OpenBlas variant of numpy in your pyinstaller exe file?
