### ISSUE TITLE
what versions of numpy do we want to support

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/numpy-feedstock#154]
it seems that the current list is:

1. 1.11
2. 1.14
3. 1.15
6. 1.16

have .12 and .13 been dropped

**Comment by rgommers** [comment]
Is there a real demand for versions that old? At SciPy'19 we'll have a discussion about a general standard/recommendation for how many versions of Python and NumPy to support in other packages. It varies now, but >4 versions of NumPy is uncommon. A decent goal for wheels would be 3 versions of Python (~4 years back) and 4 versions of NumPy (~2.5 years back). For Conda users it's much easier to upgrade, so it makes sense to be a bit less conservative than that.

Here I would suggest 1.14-1.16. Especially with having to rebuild everything for each NumPy version, it looks like a bit of a waste of resources to start building 1.11-.113 now.

**Comment by isuruf** [comment]
> Especially with having to rebuild everything for each NumPy version, it looks like a bit of a waste of resources to start building 1.11-.113 now.

This is not true. We are using the same strategy as wheels and are compiling extensions using 1.11.

**Comment by rgommers** [comment]
Oh okay, didn't know that was changed (or it was always like that and I'm misremembering).

**Comment by isuruf** [comment]
Going with @rgommers's recommendation and built 1.14. Thanks @rgommers, @hmaarrfk
