### ISSUE TITLE
Add run_constrained for `numpy-base 9999`

### ISSUE THREAD

**Issue by isuruf** [conda-forge/numpy-feedstock#160]
To avoid numpy from conda-forge and numpy-base from defaults being installed at the same time.

**Comment by jakirkham** [comment]
Would it be possible to handle this by just using strict channel priority or am I missing something?

**Comment by isuruf** [comment]
Sure, but that needs to be done before installing numpy. If somebody installs `numpy` from defaults and then added conda-forge, `numpy-base` will still be there.

**Comment by jakirkham** [comment]
Yep, though this now sounds like a documentation/best practices thing. ( https://github.com/conda-forge/conda-forge.github.io/pull/715 )
