### ISSUE TITLE
Python 3.6 aarch64 build failing (with NumPy 1.17.0)

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/numpy-feedstock#163]
The Python 3.6 aarch64 build of NumPy 1.17.0 is currently failing. Please see [this log]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=57141&view=logs&jobId=d0d954b5-f111-5dc4-4d76-03b6c9d0cf7e ) for details.

cc @conda-forge/arm-arch

**Comment by hmaarrfk** [comment]
This is likely just an other slow test that luckily passed on 3.7 

TestUFunc::test_unary_ufunc_call_fuzz 

Should probably be skipped
