### ISSUE TITLE
create a numpy116 branch

### ISSUE THREAD

**Issue by jschueller** [conda-forge/numpy-feedstock#172]
v1.17 dropped support for python 2.x, but in the meantime the blas pinnings got from 0.3.6 to 0.3.7 

if we want to avoid conflicts we must have a rerendered numpy version, could someone create a 
numpy116 branch from this commit, right before the 1.17 update ?
283ba15 numpy v1.16.4 (#158)

then I could send a pr to rerender

**Comment by chrisburr** [comment]
@conda-forge/numpy This can be closed now due to #176
