### ISSUE TITLE
Not built against the intended BLAS/LAPACK libraries on OS X?

### ISSUE THREAD

**Issue by ayshih** [conda-forge/numpy-feedstock#194]
We're trying to track down some intermittent NumPy-related bugs in SunPy that occur only when using numpy from conda-forge and only on OS X.  I understand from #143/#149 that the feedstock version is intended to build "against the netlib libraries and at runtime any provider (netlib, openblas, mkl, blis) can be used".

However, on OS X, the Accelerate libraries are [higher in priority](https://numpy.org/devdocs/user/building.html#accelerated-blas-lapack-libraries) than the NetLIB libraries (prior to NumPy 1.20).  I don't see any indication that this feedstock uses the `NPY_BLAS_ORDER`/`NPY_LAPACK_ORDER` environment variables to modify the priority order.  Is the feedstock version for OS X still being built against the (buggy) Accelerate libraries instead of the intended NetLIB libraries?

**Comment by isuruf** [comment]
> Is the feedstock version for OS X still being built against the (buggy) Accelerate libraries instead of the intended NetLIB libraries?

No
