### ISSUE TITLE
how to get the python 3 numpy from the feedstock to supercede defaults?

### ISSUE THREAD

**Issue by davidslac** [conda-forge/numpy-feedstock#21]
I am building a conda package, from a py27 based miniconda, that has

    requirements:
      build:
        - python ==3.5
    
      run:
        - python >=3.5,<4
        - numpy

and my .condarc lists conda-forge ahead of defaults. However when I install the package, I get output that includes

    The following NEW packages will be INSTALLED:
    
        ca-certificates: 2016.2.28-1            conda-forge                                      
        mkl:             11.3.3-0               defaults                                         
        numpy:           1.11.1-py35_0          defaults                                         
        python:          3.5.2-1                conda-forge                                      

I can see from https://anaconda.org/conda-forge/numpy/files that there is a linux-64/numpy-1.11.1-py35_blas_openblas_200.tar.bz2
does anyone know why I didn't pick that up?

**Comment by jakirkham** [comment]
Could you please share `conda info`?

**Comment by pelson** [comment]
Conda recently added channel priority, meaning that if `conda-forge` is defined before `defaults` in your condarc, it should pick `conda-forge` packages rather than `defaults` packages even if the conda-forge ones are older.

**Comment by davidslac** [comment]
I don't quite remember this issue, but I've reinstalled miniconda and upgraded lots of componentes, I wouldn't be able to re-create that problem now. I switched to getting numpy from defaults since the latest builds seem to work fine with the MKL. I think part of my problem was I needed to specify the numpy version on the conda build command line.

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by davidslac** [comment]
That's great!

best,

David Schneider
SLAC/LCLS
________________________________________

**Comment by pelson** [comment]
Thanks @davidslac. I think we are good to close this now, right?

**Comment by jakirkham** [comment]
Would also guess this is a channel priority issue. Switching to the 4.1.x line of `conda` should alleviate a channel priority issue. Please let us know if you re-encounter this, @davidslac.
