### ISSUE TITLE
Openblas builds broken on Windows 2004+

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/numpy-feedstock#212]
Windows 2004 has a broken `fmod` implementation in `ucrtbase.dll` that causes wrong values to be calculated - the whole saga is detailed in https://github.com/numpy/numpy/issues/16744. The numpy & openblas devs tried to fix it, but ultimately decided to just error out on `import numpy` if the bug was found: https://github.com/numpy/numpy/pull/17679

This means that the numpy builds of 1.19.4 are plainly unimportable on Windows 2004+, and this is a pretty hard break for everyone on those platforms. Given the importance of numpy & the severity of the break, tagging @conda-forge/numpy @conda-forge/core

Conda ships is own (older, unaffected) `ucrtbase.dll` in the environment, but for some reason, this is not being picked up, even with `CONDA_DLL_SEARCH_MODIFICATION_ENABLE`. @mingwandroid

<details>
<summary>Error message upon import with most recent builds</summary>

```
>>> import numpy
 ** On entry to DGEBAL parameter number  3 had an illegal value
 ** On entry to DGEHRD parameter number  2 had an illegal value
 ** On entry to DORGHR DORGQR parameter number  2 had an illegal value
 ** On entry to DHSEQR parameter number  4 had an illegal value
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\[xxx]\.conda\envs\cf\lib\site-packages\numpy\__init__.py", line 305, in <module>
    _win_os_check()
  File "C:\Users\[xxx]\.conda\envs\cf\lib\site-packages\numpy\__init__.py", line 302, in _win_os_check
    raise RuntimeError(msg.format(__file__)) from None
RuntimeError: The current Numpy installation ('C:\\Users\\[xxx]\\.conda\\envs\\cf\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```

</details>

**Comment by mbargull** [comment]
@h-vetinari, could you check if this happens for only some Python version? I.e., create environments for 3.7, 3.8, 3.9 and see if only some or all of them are affected?

**Comment by h-vetinari** [comment]
For those encountering the issue, @bashtage has made a lot of effort to document the various workarounds, both in the numpy issue and on the [windows bug tracker](https://developercommunity.visualstudio.com/comments/1244066/view.html)**:

> Some possible workarounds or mitigations. Only option 1 is completely free from the fmod bug. The others still have the bug but so far there are no reports of it appearing in test or user-code.
>
> 1.  **Python in WSL**. This is the only method on Windows 2004/H2 to completely avoid the fmod bug until a patch is released.
> 1. **conda + MKL BLAS** avoids the bug since MKL does not use the FPU in key linear algebra routines such as SVD. `conda create -n mkl python numpy`. SciPy can also be used here without encountering the fmod bug.
> 1.  **conda + OpenBLAS 0.3.12**. In high CPU count systems or in containers this may cause a problem due to changes in the default buffer size (requests about 300MiB/logical core). OpenBLAS 0.3.12 does not use the FPU on Windows. Earlier version of OpenBLAS do. `conda create -n openblas -c conda-forge python numpy blas=*=openblas`. SciPy can also be used here without encountering the fmod bug. Setting the maximum number of threads used by OpenBLAS can be used to mitigate the higher memory requirements, set `OPENBLAS_NUM_THREADS=4` or `$env:OPENBLAS_NUM_THREADS=4`.
> 1. **Use 1.19.3** Install with `pip install numpy==1.19.3` which ships with OpenBLAS 0.3.12. This has the same limitations as conda + OpenBLAS 0.3.12 with respect to memory consumption on high core count systems. If you also need SciPy, you will be exposed to the fmod bug in SciPy’s linear algebra routines since these use OpenBlas 0.3.9. The same environmental variable mitigation can be used to limit memory usage.



** somehow, linking to the comment directly doesn't seem to work for me, neither in Firefox nor Chrome.

**Comment by h-vetinari** [comment]
@mbargull, all of the following reproduce the error on import:
```
conda install python=3.7 numpy blas=*=openblas "openblas<0.3.12"
conda install python=3.8 numpy blas=*=openblas "openblas<0.3.12"
conda install python=3.9 numpy blas=*=openblas "openblas<0.3.12"
```

The good thing is that this reduces the problem "surface" a bit, in that it only happens on openblas builds (that don't use the newest version). Though the 0.3.12 version caused other problems: https://github.com/numpy/numpy/issues/17674

**Comment by bashtage** [comment]
One more workaround that escaped my initial list:

* Use 32-bit Python using `CONDA_FORCE_32BIT=1`
```cmd 
set CONDA_FORCE_32BIT=1
conda create -n python32 python numpy=1.9.2 blas=*=openblas "openblas<0.3.12"
```
or with powershell
```powershell
$env:CONDA_FORCE_32BIT=1
conda create -n python32 python numpy=1.9.2 blas=*=openblas "openblas<0.3.12"
```

**Comment by bashtage** [comment]
You can workaround the 0.3.12 OpenBLAS bug by setting the number of threads in OpenBLAS to a modest number on high core-count systems. If you only have 4 logical cores, 0.3.12 is likely to work.

```
set OPENBLAS_NUM_THREADS=4
$env:OPENBLAS_NUM_THREADS=4
```

**Comment by wolfv** [comment]
just to clarify, this is Windows 10, Version 2004, correct?

**Comment by bashtage** [comment]
Yes. Also 20H2.

**Comment by h-vetinari** [comment]
I think it's time to close this issue, as the default installs are working fine for a while now.
