### ISSUE TITLE
Rebuild with 1.16.6

### ISSUE THREAD

**Issue by xhochy** [conda-forge/numpy-feedstock#215]
To mitigate the effect from https://github.com/numpy/numpy/issues/17913, I propose that we do a NumPy migration with 1.16.6 before 1.20 gets released. Should we also change the global pinning to use 1.16.6 or do we keep that at 1.16 with the trust that the solver always picks the latest release?

Note that a precondition for this migration is that we actually build 1.16 first.

cc @conda-forge/core @conda-forge/numpy

**Comment by beckermr** [comment]
Will packages built with numpy 1.16.6 work with numpy <1.20 at runtime?

**Comment by xhochy** [comment]
Things built with 1.16.6 will work for all numpy releases `>=1.16` at runtime.

**Comment by xhochy** [comment]
The issue here is that a compiled-in macro (namely `PyArray_DescrCheck`) was buggy and the bug will only be experienced with the new class hierarchy in numpy 1.20. It's though a quite basic macro and will probably pop up in a lot of places.

**Comment by beckermr** [comment]
Ok. On osx-arm64 our pin is at 1.19.something. Is there a backported release with the fix for that platform too?

**Comment by beckermr** [comment]
Also, I would not trust the solver for this personally.

**Comment by xhochy** [comment]
I think this was fixed in all releases 1.18+ and backported to the 1.16 and 1.17 series, so where we have a pin at 1.19, we're fine.

**Comment by rgommers** [comment]
> It's though a quite basic macro and will probably pop up in a lot of places.

I did a search, and none of SciPy, Pandas, scikit-learn, scikit-image, statsmodels use it.

It may make sense to wait a day or two for the discussion on the NumPy issue to come to a conclusion. If it's a large enough problem to go rebuild a whole tree of packages on conda-forge, then the issue of breaking existing wheels may trigger the need for a workaround. Note that the final 1.20.0 release will only come out in January.

**Comment by mbargull** [comment]
Would it make sense to wait approx. 7 weeks and rebuild with a (forward compatible) 1.17 (release 2020-01-13)? Ref: https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table

**Comment by mbargull** [comment]
> Note that the final 1.20.0 release will only come out in January.

@rgommers, was a little bit faster that me ^^.

**Comment by xhochy** [comment]
> > It's though a quite basic macro and will probably pop up in a lot of places.
> 
> I did a search, and none of SciPy, Pandas, scikit-learn, scikit-image, statsmodels use it.

I could neither find it in Cython, Boost.Python nor pybind11, so it is probably limited to a very small set of packages.

**Comment by xhochy** [comment]
Closing this as I have rebuilt `pyarrow` for the last three releases with 1.16.6 and no other package should be affected.
