### ISSUE TITLE
Build broken on Python3 + Windows

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/numpy-feedstock#22]
The python 3 + window build is broken for this recipe. `import numpy` causes a `DLL import failed` error.

cf https://ci.appveyor.com/project/conda-forge/bqplot-feedstock/build/1.0.10/job/8hfk28j6qf2tathj

```
from . import multiarray
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by jakirkham** [comment]
So, we don't have a Windows build of `numpy` yet. As such, this must be a `defaults` package of `numpy` that is causing the issue. Please raise this on this [issue tracker]( https://github.com/ContinuumIO/anaconda-recipes ) with the info provided here.

**Comment by rgommers** [comment]
This issue is in the wrong repo, so closing.
