### ISSUE TITLE
Support for numpy 1.20.1

### ISSUE THREAD

**Issue by Jasha10** [conda-forge/numpy-feedstock#226]
Issue:

Numpy 1.20.1 has been released. As of this writing, this feedstock supports only 1.20.

**Comment by Jasha10** [comment]
I'd be happy to submit a PR for this, but I'm not sure about how feedstock configuration works...
Would it be enough to bump the version number and sha256 in `recipe/meta.yaml`?

**Comment by jakirkham** [comment]
There's already a PR ( https://github.com/conda-forge/numpy-feedstock/pull/225 ), but we could use your help debugging a test failure if you are interested 🙂

Going to close this issue out so we can focus efforts on that PR and getting it across the line. Thanks! 😊
