### ISSUE TITLE
load failed on OS-X 

### ISSUE THREAD

**Issue by ChrisBarker-NOAA** [conda-forge/numpy-feedstock#26]
I just did a simple update to an environment for a project that uses numpy (with the conda-forge channel enabled). then tried to run, and got:

```
ImportError: dlopen(/Users/chris.barker/miniconda2/envs/gnome/lib/python2.7/site-packages/numpy/core/multiarray.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.18.dylib
  Referenced from: /Users/chris.barker/miniconda2/envs/gnome/lib/python2.7/site-packages/numpy/core/multiarray.so
  Reason: image not found
```

`conda list` tells me I have:

`numpy                     1.11.1          py27_blas_openblas_201  [blas_openblas]  conda-forge`

I'm going to start with a clean environment and see where I can go with this, but this is not good :-(

BTW -- there are a lot of different numpy builds now -- is there any guidance on what you shuld use why? or even how to get a particular build?

**Comment by jakirkham** [comment]
Could you please share what you ran?

**Comment by ChrisBarker-NOAA** [comment]
OK: 

`conda install --file conda_requirements.txt`

and here is that file:

```
setuptools>=23.0
numpy>=1.11
scipy>=0.17
netCDF4>=1.2.2
py_gd>=0.1.5
gsw>=3.0.3
pyzmq>=15.2
cython>=0.24
psutil>=4.3
progressbar>=2.3
six>=1.10
geojson>=1.3.2
repoze.lru >= 0.6 
unit_conversion>=2.5.2
colander>=1.2
sqlalchemy>=0.7.6
zope.interface>=4.1
zope.sqlalchemy>=0.7.6
gdal>=2.0
awesome-slugify>=1.6
regex>=2016.06
unidecode>=0.04.19
cell_tree2d>=0.1.3
pyugrid>=0.2.1
pysgrid>=0.3.1

# nice to have for development, not required to run
pytest
pytest-cov
testfixtures
matplotlib
sphinx
sphinx_rtd_theme
ipython
```

Note that I have a few things in there that are not (yet) in conda-forge or defaults. They are in the NOAA-ORR-ERD channel.

here is my .condarc:

channels:
  - conda-forge
  - defaults
  - NOAA-ORR-ERD

Maybe I should keep defaults at the top??

**Comment by ChrisBarker-NOAA** [comment]
BTW, I just started a new clean (py2) environment, installed numpy, and it's fine.

Now I'm going to do the project above in a clean environment, and see what happens.

**Comment by ChrisBarker-NOAA** [comment]
OK, so now I started with a clean environment, installed from that requirements file, and numpy  works fine.

So probably an issue with upgrading to an openblas versin of numpy from a non-openblas version. But it should have installed the openblas lib, shouldn't' it?

Anyway, it's working for me, so should probably close this issue.

Thanks,
-Chris

**Comment by jakirkham** [comment]
It probably goes away if you update `openblas` too.

**Comment by ChrisBarker-NOAA** [comment]
yup -- probably should have tried that first...

thanks!

**Comment by monajalal** [comment]
```
Monas-MacBook-Pro:02_02 mona$ python
Python 3.6.1 |Anaconda custom (x86_64)| (default, May 11 2017, 13:04:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/mona/anaconda/lib/python3.6/site-packages/cv2.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblasp-r0.2.19.dylib
  Referenced from: /Users/mona/anaconda/lib/libopencv_hdf.3.2.0.dylib
  Reason: image not found
```
How should I fix this?

**Comment by jakirkham** [comment]
Please open a new issue @monajalal. Also it looks like an OpenCV issue not a NumPy one. So please redirect to that feedstock. Also please add details about your environment in that new issue. Thanks.
