### ISSUE TITLE
PyPy 3.8 or 3.9 support

### ISSUE THREAD

**Issue by thomasjpfan** [conda-forge/numpy-feedstock#260]
Now that https://github.com/conda-forge/pypy3.6-feedstock/pull/73 has been merged, is there a blocker for NumPy to be built with PyPy 3.8 or 3.9 support?

**Comment by h-vetinari** [comment]
We need someone to merge https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2601, which needs someone to test the migrator.

Building numpy directly doesn't work well, because relevant pieces like pytest etc. are missing.
