### ISSUE TITLE
libblas=*=*accelerate does not work on MacOS 14.0

### ISSUE THREAD

**Issue by PeterJohannsenCMT** [conda-forge/numpy-feedstock#301]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The following 

`conda create --name envname scipy numpy "libblas=*=*accelerate"`

throws the error 

```
PackagesNotFoundError: The following packages are not available from current channels:

  - libblas[build=*accelerate]

```

From what I can see in other fora (for instance [here](https://github.com/conda-forge/numpy-feedstock/issues/253) ), it worked with previous versions of MacOS? afaik <13.3. 

From what I can see using Accelerate makes a really big difference in numeric calculations involving scipy's sparse module, so I would really like to get that to work. 

### Installed packages

```shell
this is a brand-new Conda environment
```

### Environment info

```shell
no info to show, because I'm attempting to make a new environment
```

**Comment by isuruf** [comment]
> this is a brand-new Conda environment

Please provide this info.

> no info to show, because I'm attempting to make a new environment

Please provide this as well. `conda info`

**Comment by PeterJohannsenCMT** [comment]
> > this is a brand-new Conda environment
> 
> Please provide this info.
> 
> > no info to show, because I'm attempting to make a new environment
> 
> Please provide this as well. `conda info`

Hi, thanks for the reply. I'm not sure what to write for "installed packages", because I'm trying to set up a new environment, so theres nothing installed in the environment in question

**Comment by isuruf** [comment]
Looks like you are not using conda-forge. Please have a look at our docs on how to use conda-forge.
