### ISSUE TITLE
Packaging NumPy 2.0.0rc1

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/numpy-feedstock#311]
Recently NumPy tagged ~~[`v2.0.0b1`]( https://github.com/numpy/numpy/releases/tag/v2.0.0b1 )~~ [`v2.0.0rc1`]( https://github.com/numpy/numpy/releases/tag/v2.0.0rc1 ). This includes a number of changes documented in [these release notes]( https://github.com/numpy/numpy/blob/v2.0.0rc1/doc/source/release/2.0.0-notes.rst )

To gain familiarity with it and make it easier for developers, feedstock maintainers, etc. to test with it, think we may benefit from packaging the beta here following [CFEP 5]( https://github.com/conda-forge/cfep/blob/752a6d5cde5620ffa540012b0b384b3bbb2241fc/cfep-05.md )

Bringing this up here to discuss. Also opening for discussion of any other next steps

References:
* https://github.com/numpy/numpy/issues/24300
* https://github.com/conda-forge/conda-forge.github.io/issues/1997
* https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4816
* https://github.com/numpy/numpy/issues/26191

Edit: Updated to `2.0.0rc1` now that it is tagged and packaged. Though this was originally about `2.0.0b1`

Edit 2: Link ecosystem NumPy 2 compatibility tracking issue

**Comment by rgommers** [comment]
(disclaimer: I'm not that familiar with how pre-releases are done in conda-forge)

My current impression:
- It seems useful to package `2.0.0b1`,
- It also seems useful for projects which depend on NumPy and use the NumPy C API in nontrivial ways to have draft PRs opened to build against 2.0.0b1,
  - a little less clear if such PRs should be merged; the ABI is unlikely to change for 2.0.0rc1, but it may
  - having a larger set of builds against rc1 would make sense, it'd be quite useful to smoke out problems

Questions:
1. The `pin_compatible` mechanism will need adjusting probably. What would be preferred, having:
    - (a) builds against 1.2Xx with runtime dependency `>=1.2x,<2` and a second set of builds against numpy 2.0 with runtime dependencies `>=2.0`, or
    - (b) only build against 2.0, with runtime dependencies `>=1.2x`?
2. Would it make sense to have a migrator that gets the whole stack ready in the period between 2.0.0rc1 and 2.0.0 final?

1(b) seems nicer to me (avoids building everything twice), but I'm not sure what has to be adjusted to make that happen.

**Comment by jakirkham** [comment]
Thanks Ralf! 🙏

<hr>

We can certainly publish the `b1` packages and we can open test PRs on other feedstocks using `b1`. The test PRs could...

* Cache build artifacts (including packages) on CI
  * Primarily for testing NumPy packages themselves
  * Useful if we are concerned about API breakages (no need to worry about broken packages)
  * Smaller testing pooling (maintainers of associated feedstocks, developers on those libraries)
* Publish the downstream packages to a RC label
  * Considers broader ecosystem testing with NumPy
  * Easy to construct complex environments
  * Useful if want broader consumption of these packages (average conda-forge user)

My guess is for `b1` having open test PRs and not merging is fine. Whereas for `rc1` we may be more interested in merging. Really this is a question of what kind (and how much) testing we want to do and what level of engagement we are looking for

<hr>

The 1(a) approach is easy to roll out with our current setup. Though is more resource intensive over the long term

The 1(b) approach may take a bit more work to roll out. That said, it is lighter on resource consumption and more flexible for users

There is a bit of discussion about this particularly in issue ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4816 ). One concern is other build tools or libraries could alter settings we provide ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4816#issuecomment-1699437952 ). This is why having a way to audit binaries for NumPy compatibility ( https://github.com/numpy/numpy/pull/25948 ) would help us validate intended NumPy compatibility (or fail builds that are out of alignment)

Agree 1(b) would be nicer. Just need to make sure that we are handling the aforementioned issue correctly

A migrator would mainly be needed for 1(a). It may or may not be needed for 1(b) depending on how we handle other steps

**Comment by h-vetinari** [comment]
We should IMO clearly do 1(b). Double numpy builds until we're on 2.0+ would blow out our CI matrices.

The validation that no package scripts override `NPY_TARGET_VERSION` in contradiction with our expectation (and metadata) would be great to have, but can follow when it's ready (in the meantime, it would just be a regular packaging bug if `NPY_TARGET_VERSION` gets wrongly set and mismatches our infra; we'd be able to easily fix it per feedstock).

I've opened #312 to build 2.0.0b1 for the `numpy_dev` label.

**Comment by jakirkham** [comment]
That would be my preference as well. Though it goes beyond even CI resources and provides value to developers and end users as they can more easily test and switch between NumPy 1.x & 2.x

AIUI (and Ralf or Sebastian can correct me) [`NPY_FEATURE_VERSION` is set to `NPY_TARGET_VERSION`]( https://github.com/numpy/numpy/blob/6059db15f06555b246f3743db3152050b50722b1/numpy/_core/include/numpy/numpyconfig.h#L119-L121 ) when set. Binaries then built with NumPy's C-API would bake in `NPY_FEATURE_VERSION` thanks to PR ( https://github.com/numpy/numpy/pull/25948 ). So we should be able to check the strings of the final binaries to see whether they are built with the `NPY_TARGET_VERSION` we set (or error otherwise)

**Comment by h-vetinari** [comment]
> So we should be able to check the strings of the final binaries to see whether they are built with the `NPY_TARGET_VERSION` we set (or error otherwise)

Yeah, I think the pieces for this are mostly in place, except for the part where that test shouldn't have to be written & rewritten by every package compiling against numpy. That's the part that'll probably take a bit of figuring out.

**Comment by jakirkham** [comment]
Agreed

Some possible locations (please feel free to propose more):

1. Bake into conda-build's own package (perhaps using logic similar to [`inspect_linkages`]( https://github.com/conda/conda-build/blob/f3615dc8cced0a1ed396a05e436d68ac3f441d91/conda_build/os_utils/pyldd.py#L1101 ))
2. Include some [new test in conda-smithy feedstock templates]( https://github.com/conda-forge/conda-smithy/blob/44acb937c50ce98adf1b50b01a6ab7bc577d2fb2/conda_smithy/templates/build_steps.sh.tmpl#L101 )
3. Add logic to [feedstock output validation]( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/blob/1391177be1b88e7a11df0b824ce6a3e7bcccdb27/recipe/conda_forge_ci_setup/feedstock_outputs.py#L155 )
4. Handle in [package validation]( https://github.com/conda-forge/conda-forge-webservices/blob/82f989daa2281f1a5b3df9c39241132db718b14d/conda_forge_webservices/feedstock_outputs.py#L312-L316 )
5. ...?

**Comment by rgommers** [comment]
> The validation that no package scripts override `NPY_TARGET_VERSION` in contradiction with our expectation (and metadata) would be great to have, but can follow when it's ready (in the meantime, it would just be a regular packaging bug if `NPY_TARGET_VERSION` gets wrongly set and mismatches our infra; we'd be able to easily fix it per feedstock).

I completely agree. This is mostly an academic worry at this point, and is going to apply to very few packages in the future.

The key things are (a) to start getting the build and runtime dependencies right as soon as possible after 2.0.0rc1 is out, and (b) add a permanent metadata patch for all built packages already out there which are not ABI-compatible with the NumPy 2.x ABI.

**Comment by jakirkham** [comment]
With PR ( https://github.com/conda-forge/numpy-feedstock/pull/312 ) now merged, users can install with `conda install conda-forge/label/numpy_dev::numpy=2`

**Comment by h-vetinari** [comment]
Note that the setup here has changed a bit in order to allow the migration to proceed despite some constraints (e.g. we still have python 3.8, we need to keep strict channel priority, etc.). So as of #314, the packages here are pushed to the main conda-forge channel, but depend on `_numpy_rc`, which can only be installed from `conda-forge/label/numpy_rc`. 

So from the POV of installation, not much has changed, except that one needs to provide the channel explicitly:
```
conda install -c conda-forge/label/numpy_rc numpy=2.0.0rc1
```

Also  note that the respective label is now called "numpy_rc", as I felt that's more appropriate here than "numpy_dev"

**Comment by h-vetinari** [comment]
Since we're on 2.0.0 already for a while, I'm closing this issue - thanks all!
