### ISSUE TITLE
Backport run_exports

### ISSUE THREAD

**Issue by ZzEeKkAa** [conda-forge/numpy-feedstock#320]
### Comment:

Is it possible to backport changes in https://github.com/conda-forge/numpy-feedstock/pull/313 ? It would be nice to have it numpy 1.19 - 1.26

**Comment by h-vetinari** [comment]
Not sure what you're asking here. Numpy in conda-forge has had run-exports since 1.19, but the compatibility (i.e. the version constraints in the numpy run-export) changed fundamentally with numpy 2.0, and cannot be backported.

**Comment by jakirkham** [comment]
Could you please share more about the issue you are encountering?

**Comment by ZzEeKkAa** [comment]
Oh, okay, I just assumed that abi compatibility was for a while. In other words I was assuming if project was compiled with any python version 1.19 - 1.26 it will be compatible with `>=1.19,<2`, not `>=compiled version,<2`. If it is the case only starting from the v2, then there is no issue.

**Comment by jakirkham** [comment]
No NumPy didn't introduce [the new ABI compatibility until NumPy 1.25.0]( https://numpy.org/doc/stable/release/1.25.0-notes.html#compiling-against-the-numpy-c-api-is-now-backwards-compatible-by-default )

We discussed whether we wanted to change things then ( https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/4816 ). However we decided it wasn't worth the effort as we could do this with NumPy 2 (when we already would need to change things)

So the approach we are taking is rebuild everything with NumPy 2 (as we need to anyways) and use the new ABI there. The packages produced work on NumPy 1 & 2, which is a bigger benefit for users then slightly more compatibility with NumPy 1 versions (and no NumPy 2 support)

**Comment by ZzEeKkAa** [comment]
Yes, that totally makes sense! Thank you for explaining!
