### ISSUE TITLE
numpy + mkl + osx-64 detection broken??? with cmake 3.30.0

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/numpy-feedstock#327]
### Comment:

We found that pytorch silently disabled numpy's features when cmake 3.30.0 failed to find numpy.

Pytorch didn't call it "required", so it moved on.

I feel like the patch added in
https://gitlab.kitware.com/cmake/cmake/-/commit/df551ee53875bbfc888d92c7c523c9b6b2154283#
is wrong for conda-forge.... Looking at the tags, it seems to have been introduced in 3.30.0

I'm posting here instead of cmake since I feel like this will get the best "eyes" for those that care about this issue.

xref: https://github.com/numpy/numpy/issues/23775
xref: https://gitlab.kitware.com/cmake/cmake/-/blob/v3.30.2/Modules/FindPython/Support.cmake?ref_type=tags#L3906
        
I am likely going to add a workaround:

```yaml
        - cmake !=3.30.0,!=3.30.1,!=3.30.2        # [osx and blas_impl == "mkl"]
        - cmake                                   # [not (osx and blas_impl == "mkl")]
```

and a test to ensure we are more proactive about this at the pytorch feedstock: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/252

cc: @conda-forge/cmake 

First symptom found in:
xref: https://github.com/conda-forge/torchani-feedstock/pull/39

**Comment by h-vetinari** [comment]
From reading the numpy issue, the workaround committed into CMake 3.30 should be the one that works, though the information from the [intel forum](https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/CPU-Deprecation-Warning/m-p/1549616/highlight/true#M35531) is about 9 month old. Perhaps newer MKL has changed behaviour yet again?

**Comment by hmaarrfk** [comment]
I'm recreating the failure in: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/253#issuecomment-2308811052

What worries me is that in 2023, [rgommers said](https://github.com/numpy/numpy/issues/23775#issuecomment-1554278791):

> The conda-forge channel gets this right [...]

but i could be taking this out of context....

the latest version of  OSX-64 mkl is 2023.2 and was uploaded 9 months ago.... so i don't know if anything has changed
![image](https://github.com/user-attachments/assets/d0c24c88-d8e6-4dd4-bc32-2cc75399d04d)
https://anaconda.org/conda-forge/mkl/files?version=2023.2.0

the most recent recipe skips not linux/win: https://github.com/conda-forge/intel_repack-feedstock/blob/main/recipe/meta.yaml#L104

**Comment by h-vetinari** [comment]
> the latest version of OSX-64 mkl is 2023.2 and was uploaded 9 months ago.... [...] 
> the most recent recipe skips not linux/win

See https://github.com/conda-forge/intel_repack-feedstock/issues/62

> What worries me is that in 2023, [rgommers said](https://github.com/numpy/numpy/issues/23775#issuecomment-1554278791):
> 
> > The conda-forge channel gets this right [...]

AFAIU Ralf was talking about not getting a x64 MKL on an M1 machine run through rosetta, but rather a natively arm64 BLAS implementation (which then isn't MKL in the first place).

> I'm recreating the failure in: [conda-forge/pytorch-cpu-feedstock#253 (comment)](https://github.com/conda-forge/pytorch-cpu-feedstock/pull/253#issuecomment-2308811052)

Thanks for that PR! I pushed a commit to test another approach there.

**Comment by h-vetinari** [comment]
Raised https://gitlab.kitware.com/cmake/cmake/-/issues/26240

**Comment by hmaarrfk** [comment]
I feel like we might just want to revert that patch for conda-forge while they figure it out upstream.

I'm trying to delete the "set env" changes and checking if that resolves things at pytorch.

**Comment by h-vetinari** [comment]
> while they figure it out upstream.

There's https://gitlab.kitware.com/cmake/cmake/-/merge_requests/9776 now. Not sure if it works, but I wanted to try if setting the variable to `AVX` works

**Comment by hmaarrfk** [comment]
that was fast...

**Comment by hmaarrfk** [comment]
Unfortunately , i don't think that it had the desired effect.

You can see the results of https://github.com/conda-forge/pytorch-cpu-feedstock/pull/253

and to make the failure faster, I've written a small patch that I've included in https://github.com/conda-forge/pytorch-cpu-feedstock/pull/259

**Comment by hmaarrfk** [comment]
i think this has been resolved?

**Comment by jakirkham** [comment]
In that case, would you like to close it?
