### ISSUE TITLE
Question: Do maintainers currently plan to produce a 1.x build for Python 3.13?

### ISSUE THREAD

**Issue by maresb** [conda-forge/numpy-feedstock#343]
### Comment:

Thanks a lot to the maintainers for all their work on this feedstock.

Just for planning purposes (no pressure), I'm wondering if the current maintainers have the intention to produce a 1.x build for Python 3.13? A simple yes/no would suffice.

(Unfortunately I have neither the time or the expertise to do this myself.)

**Comment by rgommers** [comment]
No, that isn't desirable I think, since numpy 2.1.0 is the first version to support Python 3.13. It would be confusing to offer 1.26 + 3.13, even if it were technically possible to backport a lot of the needed fixes.
