### ISSUE TITLE
Problem with numpy/openblas in staged-recipes

### ISSUE THREAD

**Issue by jochym** [conda-forge/numpy-feedstock#42]
Several (phonopy, elastic, pyhmc) staged-build PRs got broken by the numpy/openblas problems on osx and linux for py3k. I had to block builds for py3k on these platforms. At the same time the feedstocks with similar code and setup (e.g. spglib) build fine. I'll be happy to provide any additional info to help with this.

**Comment by jakirkham** [comment]
The fact that this occurs in staged-recipes and not the feedstocks leads me to believe it is not a problem with NumPy, OpenBLAS, etc. Instead it sounds like a `conda-build-all` issue. Given `conda-build-all` is only used to run builds at staged-recipes and the kind of issue is related to how `conda-build-all` reuses environments, this sounds like the cause.

Should note a potential related problem occurs with Python 3.4 at staged-recipes that appears to be solved by upgrade to `conda-build` 2. Might be worth trying something similar for this case. If it does solve it, this implies there is some issue with `conda-build-all`/`conda-build` compatibility and needs to be raised at the `conda-build-all` issue tracker.

xref: https://github.com/conda-forge/staged-recipes/pull/2096#issuecomment-268261540
xref: https://github.com/SciTools/conda-build-all

**Comment by jakirkham** [comment]
Pinning to `conda-build-all` version `1.0.0` fixes this problem. However, that means a bug crept into `conda-build-all` version `1.0.1`. Namely something is off with PR ( https://github.com/SciTools/conda-build-all/pull/68 ).

**Comment by jakirkham** [comment]
Opened an issue with `conda-build-all` as that appears to be the source of the problem.

xref: https://github.com/SciTools/conda-build-all/issues/75
