### ISSUE TITLE
openBlas numpy tries to load mkl

### ISSUE THREAD

**Issue by kain88-de** [conda-forge/numpy-feedstock#64]
@MDAnalysis/coredevs @orbeckst @richardjgowers 

MDAnalysis is seeing build failures on travis for a day now. They are persistent on python 3.6 with the recent numpy from conda-forge ([travis log](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/281580290), [installs mkl](https://travis-ci.org/MDAnalysis/mdanalysis/jobs/281580290#L1358)). This problem causes our tests to crash. I can reproduce a crash in one of the tests on my own laptop.

*Error Message*

```python

In [1]: from MDAnalysisTests.datafiles import PSF, DCD

In [2]: u = mda.Universe(PSF, DCD)

In [3]: u.transfer_to_memory()

In [4]: from MDAnalysis.analysis import encore

In [5]: r ,d = encore.dres([u, u])
Intel MKL FATAL ERROR: Cannot load libmkl_avx2.so or libmkl_def.so.
```

In case this is of interest here is the update message I got today for numpy.

*Updating numpy today*

```
1d [max:~/code … MDAnalysisTests] [mda] travis-pytest-check+* 58s ± conda update numpy
Fetching package metadata ...............
Solving package specifications: .

Package plan for installation in environment /home/max/anaconda3/envs/mda:

The following NEW packages will be INSTALLED:

    mkl:          2017.0.3-0                               

The following packages will be UPDATED:

    biopython:    1.70-np112py36_1              bioconda    --> 1.70-py36_1                   conda-forge
    numba:        0.35.0-np112py36_0                        --> 0.35.0-np113py36_0                       
    numpy:        1.12.1-py36_blas_openblas_200 conda-forge [blas_openblas] --> 1.13.2-py36_blas_openblas_200 conda-forge [blas_openblas]
    openblas:     0.2.19-2                      conda-forge --> 0.2.20-1                      conda-forge
    pytables:     3.4.2-np112py36_1             conda-forge --> 3.4.2-np113py36_1             conda-forge

The following packages will be DOWNGRADED:

    scikit-learn: 0.19.0-py36_blas_openblas_201 conda-forge [blas_openblas] --> 0.19.0-np113py36_0                       
    scipy:        0.19.1-py36_blas_openblas_202 conda-forge [blas_openblas] --> 0.19.1-np113py36_0    
```

**Comment by jakirkham** [comment]
It looks like what is happening is some things are using `openblas` and some things are not. In particular `scipy` and `scikit-learn` are not using `openblas`. Mixing two different BLASes like this is known to have issues.

The problem is we rebuilt `numpy` with the new `openblas`, but were unable to rebuild `scipy` or anything else with it as 0.2.20 is buggy. So the `conda` solver is wiggling out of the dependency constraint. If you force `openblas` 0.2.19, that should fix the issue.

Though we should definitely switch `numpy` back to `openblas` 0.2.19 until upstream makes `openblas` 0.2.21.

**Comment by kain88-de** [comment]
> Though we should definitely switch numpy back to openblas 0.2.19 until upstream makes openblas 0.2.21.

yeah that would be nice. Debugging this without information how packages on conda-forge are build seems almost impossible.

**Comment by jakirkham** [comment]
Do you mind submitting a PR? Would do it myself, but will be away from my laptop for most of the day.
