### ISSUE TITLE
Latest openblas numpy broken?

### ISSUE THREAD

**Issue by pmlandwehr** [conda-forge/numpy-feedstock#66]
Hey all,

On my mac running python 2.7, when I updated to the latest conda-forge `numpy` (`1.12.1-py27_blas_openblas_200 conda-forge [blas_openblas]`) I get an immediate crash on import and a report of a broken build:

```python
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
```

Switching to anaconda's `numpy` fixes this entirely, but I'm unclear why the build is broken.

**Comment by jakirkham** [comment]
The latest version is 1.13.3. How is 1.12.1 coming up?

**Comment by jakirkham** [comment]
Could you please add the environment details?

**Comment by isuruf** [comment]
Can you try with an openblas build with https://github.com/conda-forge/openblas-feedstock/pull/35 ?

**Comment by pmlandwehr** [comment]
Which details would you like? Key points:
* OS X 10.12.6
* `python 2.7`

```bash
$ conda list conda
# packages in environment at /opt/anaconda2:
#
anaconda                  custom                   py27_0  
anaconda-client           1.6.3                    py27_0  
anaconda-navigator        1.6.2                    py27_0  
anaconda-project          0.6.0                    py27_0  
conda                     4.3.27           py27h94ab009_0    anaconda
conda-env                 2.6.0                h36134e3_0    anaconda
$ 
```

**Comment by pmlandwehr** [comment]
It seems that I've been kept to `1.12` by `engarde`:
```bash
$ conda install numpy=1.13.*
Fetching package metadata .............
Solving package specifications: .

UnsatisfiableError: The following specifications were found to be in conflict:
  - engarde -> numpy 1.12*
  - numpy 1.13.*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jakirkham** [comment]
I think this got fixed with PR ( https://github.com/conda-forge/engarde-feedstock/pull/5 ). So am closing. Though please let us know if that is not the case.
