### ISSUE TITLE
NumPy 1.14 on Window requires flang.lib when compiling C extensions

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/numpy-feedstock#79]
When compiling a C extension which uses NumPy 1.14 the linker seems to be requiring `flang.lib` and other libraries.  For example this build of [arm_pyart](https://ci.appveyor.com/project/conda-forge/arm-pyart-feedstock/build/1.0.23/job/tkrovt6o06vn4d1g#L810).  

The immediate issue can be solved by building against an older NumPy and relying on NumPy's backwards compatibility.

**Comment by ocefpaf** [comment]
Argh... I'll remove the Windows packages, again, and we can talk about a better strategy in this later.

Thanks for the report @jjhelmus

**Comment by xoviat** [comment]
That's not what is happening. You're [trying to compile](https://github.com/ARM-DOE/pyart/blob/f0dd0a64de9891ef6aa0ea5378141a7551d53686/pyart/retrieve/setup.py) fortran code without the flang dependency.

Note: NumPy thinks that the flang compiler works (`config.have_f90c()`) because of the `numpy->openblas->openmp->clangdev` dependency, which provides an executable named `flang` that doesn't work when the `flang` package is not installed.

**Comment by xoviat** [comment]
Possible solutions to this problem:
1. Move the `flang.exe` executable out of the `clangdev` package (not in favor).
2. Modify NumPy to check that the Fortran compiler actually works before trying to use it (possibly in favor).
3. Telling downstream users to use flang to compile Fortran code (no changes required here; enables modules that require Fortran; in favor).

**Comment by jjhelmus** [comment]
@xoviat You are correct, this seems to be caused by the fact that arm_pyart has both C and Fortran code.  

I tried compiling pywavelets, which only has C code, against NumPy 1.14 and [everything is fine](https://ci.appveyor.com/project/conda-forge/pywavelets-feedstock/build/1.0.30/job/nhgjoy1v4r7xi6ea).

In the arm_pyart example what I don't understand is why "flang.lib flangrti.lib ompstub.lib" are being added to the link arguments for the _sigmetfile module which is a C extension.   

arm_pyart has [logic to skip extensions](https://github.com/ARM-DOE/pyart/blob/v1.9.0-picasso/pyart/retrieve/setup.py#L18-L30) which use Fortran, but this logic depends on `config.have_f90c()` returning False.  It sounds like this logic will need to be updated

**Comment by xoviat** [comment]
> Any idea why this issue doesn't affect us when using Intel Fortran to build NumPy?

Intel Fortran runtime libraries don't depend on a compiler package. For example, the intel-openmp package doesn't depend on having ifort installed.

> Also why is there a flang.exe in clangdev? Seems like a poor separation of concerns.

The modified clangdev that we provide contains a Fortran compiler driver. However, the code generation is done in the flang package.

> In the arm_pyart example what I don't understand is why "flang.lib flangrti.lib ompstub.lib" are being added to the link arguments for the _sigmetfile module which is a C extension.

Compiler libraries are applied globally. When you enable the Fortran compiler, all of your extensions get the Fortran libraries. Same with a custom C compiler.

**Comment by xoviat** [comment]
One idea is to create a new flang-driver package that is just the flang executable and have it depend on clangdev (similar to how we split libflang out).

cc @isuruf

**Comment by jjhelmus** [comment]
> Compiler libraries are applied globally. When you enable the Fortran compiler, all of your extensions get the Fortran libraries. Same with a custom C compiler.

Good to know, thanks for the help.  

Since this is not an issue with NumPy itself I'm closing this.  I would be in favor of re-adding the Windows NumPy 1.14 packages to the `main` label and removing them from `broken`.

**Comment by xoviat** [comment]
The issue that I've opened at clangdev-feedstock should fix the `config.have_f90c()` function.

**Comment by jjhelmus** [comment]
> The issue that I've opened at clangdev-feedstock should fix the config.have_f90c() function.

Sounds good, this seems in-line with the docstring section, "True if a Fortran 90 compiler is available (because a simple Fortran 90 code was able to be compiled successfully)"
