### ISSUE TITLE
scipy feedstock is disabled for win_amd64, causes dependency clash with MKL

### ISSUE THREAD

**Issue by mikofski** [conda-forge/numpy-feedstock#82]
### proposal
I think that the conda-forge numpy-feedstock should be disabled for win_amd64 until the [scipy-feedstock](../../scipy-feedstock) is available for win_amd64. In the future I think these two should always be available conjoined for any given platform.

### description
On win-amd64 platform, in new conda env with conda-forge as highest priority, SciPy fails test: `scipy.linalg.tests.test_basic.TestDet` if NumPy is installed **first** using this feedstock, and then SciPy is installed afterwards.

### system info
platform: win_amd64
anaconda: miniconda
conda: 4.5.1

### procedure
this is what I did:
```
> conda create -n forge
> conda activate forge
> conda config --env --add channels conda-forge
> conda install python=3 pip setuptools wheel
> conda install pytest nose
> conda install numpy
> conda list
```
at this point numpy shows as installed from conda-forge channel with OpenBLAS, if I run `numpy.show_config()` I see that it uses openblas, and `numpy.test()` all pass.

then I add scipy
```
>conda install scipy
>python
...
>>> import scipy
>>> scipy.test()
```
this installs scipy from the default channel, as well as mkl, icc, intel-openmp, etc. If I open python and run `scipy.show_config()` I see it uses MKL, but if I run `scipy.test()` it fails `scipy.linalg.tests.TestDet().test_random()` and hangs for several minutes or longer on `test_random_complex()`

### more information
There's a full stacktrace of the scipy test failures and other anecdotal info in these posts:
* [scipy-dev mailing list: "SciPy in conda-forge env on Windows"](https://mail.python.org/pipermail/scipy-dev/2018-April/022779.html)
* [conda-forge google group: "dependency clash for SciPy on Windows with default"](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/conda-forge/PPLWn4U1ZHA/frHthukWCgAJ)

**Comment by ocefpaf** [comment]
This is ultimately a `conda` "bug" b/c it does not handle correctly the concept of conflicts. That makes installing packages in an existing env always troublesome.

The only solution is to start a fresh env with all the packages you want and hope that the solver will do the right thing. Removing the Windows `numpy` is not an option though.

PS: ping @isuruf who was really close to have a working `scipy` with `openblas` on Windows.
