### ISSUE TITLE
MKL-FFT Issue on Numpy 1.15 on Windows 32bit, Py3.5

### ISSUE THREAD

**Issue by ax3l** [conda-forge/numpy-feedstock#97]
Since the latest build update, I error in `import numpy as np` with:

```
11: Test timeout computed to be: 1500
11: Traceback (most recent call last):
11:   File "C:/projects/openpmd-api/build/bin/3_write_serial.py", line 10, in <module>
11:     import numpy as np
11:   File "C:\Miniconda35\lib\site-packages\numpy\__init__.py", line 158, in <module>
11:     from . import fft
11:   File "C:\Miniconda35\lib\site-packages\numpy\fft\__init__.py", line 15, in <module>
11:     import mkl_fft._numpy_fft as _nfft
11:   File "C:\Miniconda35\lib\site-packages\mkl_fft\__init__.py", line 27, in <module>
11:     from ._pydfti import (fft, ifft, fft2, ifft2, fftn, ifftn, rfft, irfft,
11:   File "mkl_fft\_pydfti.pyx", line 32, in init mkl_fft._pydfti
11: NameError: name 'ModuleNotFoundError' is not defined
```

https://ci.appveyor.com/project/ax3l/openpmd-api/build/1.0.515/job/rxaynqq4issl7q5y
https://github.com/openPMD/openPMD-api/blob/3a26c963cd14a00f75ecf39e725237bb6cbdc94a/.appveyor.yml

Machine:
- AppVeyor, Windows 32bit
- miniconda35

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda install -n root --quiet --yes cmake hdf5 numpy

Package plan for installation in environment C:\Miniconda35:
The following NEW packages will be INSTALLED:
    blas:            1.0-mkl               defaults   
    ca-certificates: 2018.4.16-0           conda-forge
    cmake:           3.11.1-0              conda-forge
    hdf5:            1.10.2-vc14_0         conda-forge [vc14]
    icc_rt:          2017.0.4-h97af966_0   defaults   
    intel-openmp:    2018.0.3-0            defaults   
    mkl:             2018.0.3-1            defaults   
    mkl_fft:         1.0.4-py35_0          conda-forge
    mkl_random:      1.0.1-py35_0          conda-forge
    numpy:           1.15.0-py35h9fa60d3_0 defaults   
    numpy-base:      1.15.0-py35h4a99626_0 defaults   
    zlib:            1.2.11-vc14_0         conda-forge [vc14]
The following packages will be UPDATED:
    conda:           4.3.30-py35hf722ebf_0 defaults    --> 4.5.1-py35_0  conda-forge
    openssl:         1.0.2l-vc14_0         defaults    --> 1.0.2o-vc14_0 conda-forge [vc14]
    pycosat:         0.6.1-py35_1          defaults    --> 0.6.3-py35_0  conda-forge
The following packages will be SUPERSEDED by a higher-priority channel:
    conda-env:       2.6.0-0               defaults    --> 2.6.0-0       conda-forge
```
</details>

**Comment by ocefpaf** [comment]
You are getting `numpy` from `defaults`:

```
    numpy:           1.15.0-py35h9fa60d3_0 defaults 
```

I recommend you to add `conda-forge::numpy` to your envs to ensure ou get conda-forge's version. Conda's channel preference does not work as we expect and that mixing of channel there is the source of your problems.

**Comment by ax3l** [comment]
I just found #84 and it looks I am using the "stock" numpy instead of this conda-forge feed. Will change the channel!

**Comment by ax3l** [comment]
@ocefpaf yes, thanks! Just saw it at the same moment!

**Comment by ax3l** [comment]
@ocefpaf sorry for the stupid question: how do I switch from an already installed `default` (MKL-powered) numpy to the `conda-forge` version? Just a plain `conda install -c conda-forge numpy` seems not to change it.

**Comment by ocefpaf** [comment]
Try `conda install --channel conda-forge conda-forge::numpy`.

**Comment by ax3l** [comment]
Thanks!
Just realized `conda-forge` does not publish 32-bit windows binaries, so I can't use this channel :(

**Comment by ocefpaf** [comment]
> Just realized conda-forge does not publish 32-bit windows binaries, so I can't use this channel on my AppVeyor CI script :(

Yep. We cannot afford to build win-32 due to CI limitations.

**Comment by ax3l** [comment]
No problem, I am now just installing `numpy==1.14.5` as of the previous release on the win-32.

Do you know where I can report bugs to the `default` channel for their numpy 1.15.0?

**Comment by ocefpaf** [comment]
> Do you know where I can report bugs to the default channel for their numpy 1.15.0?

@msarahan what is the preferred way to report bugs for packages on defatuls?
Is it https://github.com/AnacondaRecipes?

**Comment by ax3l** [comment]
I think the reason for the crash was: I had `mkl_fft` from `conda-forge` but `numpy 1.15.0` from `default`. Fixed both to default now and it works, so It's just the dependency that was not consistency resolved to `default` with `conda install`.
https://ci.appveyor.com/project/ax3l/openpmd-api/build/1.0.526

**Comment by msarahan** [comment]
You are mixing conda forge mkl_fft and mkl_random with defaults numpy.
You're probably seeing binary incompatibility issues. Try to install all of
those packages from just one channel.

**Comment by msarahan** [comment]
Your problem was actually a bug in mkl_fft.
https://github.com/IntelPython/mkl_fft/pull/17#issuecomment-408429328

It works in defaults because we patched it.

**Comment by ax3l** [comment]
Thanks a lot, that's it! :)
